# Generated by Django 4.1.2 on 2022-11-02 22:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description_short', models.TextField(blank=True, max_length=1000, null=True)),
                ('description_detail', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('cleaning', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(max_length=20)),
                ('price_sale', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='images')),
                ('avatar_flip', models.ImageField(default=None, null=True, upload_to='images')),
                ('color', models.CharField(default=None, max_length=255)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('specs', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('ean13', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productbranch')),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
        migrations.AddField(
            model_name='productbranch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcatalogue'),
        ),
        migrations.CreateModel(
            name='ListSizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(max_length=255)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.FileField(upload_to='files')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productitem')),
            ],
            options={
                'ordering': ['idProduct'],
                'unique_together': {('album', 'idProduct')},
            },
        ),
    ]
