# Generated by Django 4.1.2 on 2022-11-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-idProduct']},
        ),
    ]
